### ISSUE TITLE
centos 7 一直提示错误，.net环境已装

### ISSUE THREAD

**Issue by dmhai** [eaglexiang/eagle.tunnel.dotnet.core#1]
centos 7 一直提示 No executable found matching command "dotnet-./bin/eagle.tunnel.dotnet.core"，

但是.net环境我是装了的，/etc/profile 也配置了，直接执行dotnet可以看到参数提示界面。

能否做个详细点的教程？

**Comment by eaglexiang** [comment]
@dmhai 可以参考这个教程来做：[https://www.eaglexiang.org/eagle-tunnel](https://www.eaglexiang.org/eagle-tunnel) 
你遇到的问题应该是出在那个短横线-上，将它替换成空格，再根据教程在后面加上合适的参数应该就可以了。

**Comment by eaglexiang** [comment]
@dmhai 教程和软件都已经有较大更新，希望已经解决您的问题。

我会先关掉这个issue，如果还有其它问题欢迎再提。
