### ISSUE TITLE
dotnet进程自动关闭

### ISSUE THREAD

**Issue by Shaun-Fong** [eaglexiang/eagle.tunnel.dotnet.core#10]
Linux centos 7

服务开启正常，监听刚开始正常

发现代理无效之后我就查看服务器监听的端口，发现并没有8080，于是我重启服务
dotnet监听的8080端口又回来了

然后我再尝试连接，发现一连接dotnet自动消失了。。。

@eaglexiang

**Comment by eaglexiang** [comment]
可以通过命令
```shell
journalctl -xe
```
或
```
less /var/log/eagle-tunnel/output.log
less /var/log/eagle-tunnel/error.log
```
查看错误日志。

**Comment by Shaun-Fong** [comment]
[root@host ~]# journalctl -xe
Jun 29 18:56:16 host.localdomain dotnet[1547]: System.Collections.Generic.KeyNotFoundException: The given key 'anonymou
Jun 29 18:56:16 host.localdomain dotnet[1547]: at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFound
Jun 29 18:56:16 host.localdomain dotnet[1547]: at eagle.tunnel.dotnet.core.EagleTunnelHandler.CheckAuthen(Tunnel tunnel
Jun 29 18:56:16 host.localdomain dotnet[1547]: at eagle.tunnel.dotnet.core.EagleTunnelHandler.Handle(String firstMsg, T
Jun 29 18:56:16 host.localdomain dotnet[1547]: at eagle.tunnel.dotnet.core.RequestHandler.Handle(Tunnel tunnel) in /mnt
Jun 29 18:56:16 host.localdomain dotnet[1547]: at eagle.tunnel.dotnet.core.Server._handleClient(Object socket2ClientObj
Jun 29 18:56:16 host.localdomain dotnet[1547]: at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object pa
Jun 29 18:56:16 host.localdomain dotnet[1547]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext execut
Jun 29 18:56:16 host.localdomain dotnet[1547]: --- End of stack trace from previous location where exception was thrown
Jun 29 18:56:16 host.localdomain dotnet[1547]: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Jun 29 18:56:16 host.localdomain systemd[1]: eagle-tunnel.service: main process exited, code=killed, status=6/ABRT
Jun 29 18:56:16 host.localdomain systemd[1]: Unit eagle-tunnel.service entered failed state.
Jun 29 18:56:16 host.localdomain systemd[1]: eagle-tunnel.service failed.
Jun 29 18:56:16 host.localdomain systemd[1]: eagle-tunnel.service holdoff time over, scheduling restart.
Jun 29 18:56:16 host.localdomain systemd[1]: start request repeated too quickly for eagle-tunnel.service
Jun 29 18:56:16 host.localdomain systemd[1]: Failed to start Eagle Tunnel Server Service.
-- Subject: Unit eagle-tunnel.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit eagle-tunnel.service has failed.
-- 
-- The result is failed.
Jun 29 18:56:16 host.localdomain systemd[1]: Unit eagle-tunnel.service entered failed state.
Jun 29 18:56:16 host.localdomain systemd[1]: eagle-tunnel.service failed.


/var/log/eagle-tunnel/
目录下没有日志文件

@eaglexiang

**Comment by eaglexiang** [comment]
已修复，可在eagle-tunnel的下载目录里执行以下命令更新到最新：

```shell
git pull
git submodule update
./build
sudo ./install
```

更新后会覆盖配置文件，可重新配置，也可提前备份。

**Comment by Shaun-Fong** [comment]
The problem has been solved successfully!thanks! @eaglexiang
