### ISSUE TITLE
unalias: cp: not found

### ISSUE THREAD

**Issue by ykfq** [eaglexiang/eagle.tunnel.dotnet.core#2]
作者辛苦，临晨5点还在更新。

执行 `./build.sh` 脚本时提示
>./scripts/buildRelease.sh: line 33: unalias: cp: not found

![image](https://ws3.sinaimg.cn/mw690/6ee6fa3egy1fskw1llgq7j214o08eab7.jpg)

我简单修改了脚本`./scripts/buildRelease.sh` cp 和 mv 为绝对路径, 再次执行就正常了。  
![image](https://ws4.sinaimg.cn/mw690/6ee6fa3egy1fskwxoicl5j20k204iwev.jpg)

系统：
CentOS 7.5

**Comment by eaglexiang** [comment]
谢谢。

我在有限的环境里测试后显示，这里的报错应该是不会影响正常编译才对。这一句的本意是避免由于部分发行版alias过cp命令造成的不必要的提示信息。

希望能帮忙测试一下，如果保留这一句，在仍然报错`unalias: cp: not found`的情况下，是否会导致cp命令和mv命令的失效。具体检查，在执行`./build.sh`之后，`publish/etc/eagle-tunnel.conf`文件是否存在就可以了。

**Comment by ykfq** [comment]
我再两台新机器上都遇到这个错误，这个报错直接导致脚本退出了，build 没有成功。

**Comment by eaglexiang** [comment]
好，那我将它去掉。谢谢了
