### ISSUE TITLE
Failed to parse output specifier, ignoring: file:/var/log/eagle-tunnel/output.log

### ISSUE THREAD

**Issue by ykfq** [eaglexiang/eagle.tunnel.dotnet.core#3]
服务器启动后，通过 `sudo systemctl status eagle-tunnel.service` 查看服务状态正常，发现有错误：
> systemd[1]: [/usr/lib/systemd/system/eagle-tunnel.service:10] Failed to parse output specifier, ignoring: file:/var/log/eagle-tunnel/output.log
> systemd[1]: [/usr/lib/systemd/system/eagle-tunnel.service:11] Failed to parse output specifier, ignoring: file:/var/log/eagle-tunnel/error.log

简单分析是写日志的目标目录不存在。

手动创建后重启服务，错误就没有了。
```
mkdir -pv /var/log/eagle-tunnel
sudo systemctl restart eagle-tunnel.service
```

`netstat -ntlp` 端口没有正常监听,  检查发现是我我在配置文件中将 vps ip写成了公网ip，改成内网ip，重启服务后正常了。

**Comment by eaglexiang** [comment]
> 手动创建后重启服务，错误就没有了

谢谢，脚本里的确有一句mkdir -p /var/log/eagle-tunnel，抱歉不是很熟悉，不清楚是否跟缺少v参数有关系。不过我将v参数添加进去吧。

> 检查发现是我我在配置文件中将 vps ip写成了公网ip，改成内网ip，重启服务后正常了。 

请问这句是什么意思？是程序无法正常监听公网IP的8080端口吗？8080端口是否被别的程序占用？如果修改端口为别的不常见端口号，是否能正常工作呢？

如果更改VPS IP为内网IP，程序运行应该没问题，不过客户端就无法与服务端连通了吧

修改端口号的方法：https://github.com/eaglexiang/eagle.tunnel.dotnet.core/blob/master/doc/guide.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%AF%E5%8F%A3%E5%8F%B7

**Comment by ykfq** [comment]
第一个问题，跟 `-v`没关系，加`-v`只是把执行结果显示出来，不加不会显示。

第二个问题，我的vps，vps厂商配置的是内网ip，公网IP是配置在外部的，因此端口不能监听在一个本机不存在的ip上，这个问题应该是正常的。 内网监听什么端口，对应的公网IP也会监听这个端口的，相当于被映射出去了。

**Comment by eaglexiang** [comment]
另有一个issue也提到了日志文件目录自动创建失败的问题。

请问你的操作系统版本是什么？我在CentOS 7.5与Ubuntu Server 18.04、Archlinux中分别测试，均能成功创建`/var/log/eagle-tunnel`。我想知道是否是由发行版的不同引发的。

**Comment by eaglexiang** [comment]
由于取消了独立的日志文件，这个问题应该不会存在了
