### ISSUE TITLE
老铁，没法用啊

### ISSUE THREAD

**Issue by ykfq** [eaglexiang/eagle.tunnel.dotnet.core#4]
安装完服务端后，使用如下方式尝试上网，无果，请求协助：
- 在国内vps上安装客户端，本机电脑配置代理服务器 xx.xx.xx.xx:xxxx , 无法代理上网；
- 在本机电脑（win10 x64）安装客户端
  - 最新版 1.6 exe格式，安装完成无法启动服务（点击后没有界面出现）；
  - 早期 1.4 msi 格式，安装完成后有wiki中的界面，无论是配置国外vps ip:port 还是国内客户端的 ip:port, 都无法实现代理上网

**Comment by eaglexiang** [comment]
请问是否安装过dotnet core的运行库。

**Comment by ykfq** [comment]
都是按照你的脚本执行的，安装过程中有提示安装300多M的 dotnet相关文件。

**Comment by eaglexiang** [comment]
是这样的，应该在vps上安装服务端，在本地安装客户端。服务端Listen填服务端IP，客户端Relayer填服务端IP，Listen填客户端IP，系统里填客户端IP。

客户端必须搭建在本地。vps上搭建客户端，本地是访问不到的，会被屏蔽（而且ip有被ban的风险）。本地能访问什么内容取决于vps上能访问什么内容。

使用服务端和客户端的机器都分别需要安装dotnet core，本地如果是Windows，需要自行下载安装，教程刚开始有提供下载的官网：

https://www.microsoft.com/net/download/windows

**Comment by eaglexiang** [comment]
过去时间太长，这个问题恐怕很难在新版本中复现了
