### ISSUE TITLE
第一步配置就出了问题

### ISSUE THREAD

**Issue by banbadaowd** [eaglexiang/eagle.tunnel.dotnet.core#5]
老板，对于我们这种小白，能否开发一个一键脚本哈？？
我第一步  sudo ./scripts/dotnet/centos.sh   就提示没有这个命令
一脸懵逼啊，我也你一样用的也是vultr 的服务器，Linux版本都一样。

这个隧道那么好，我还是希望能方便我们这种小白哈。

**Comment by eaglexiang** [comment]
很抱歉，是我更新文档的时候出了问题，写错了步骤顺序。需要先下载ET，才能使用其中附带的脚本。
麻烦跟随最新的文档重新操作：
https://github.com/eaglexiang/eagle.tunnel.dotnet.core/blob/master/doc/guide.md

**Comment by eaglexiang** [comment]
一键安装脚本是很方便的东西，未来一定会有的，希望能早点完工😁


祝您愉快



________________________________
发件人: banbadaowd <notifications@github.com>
发送时间: 2018年6月23日 22:14
收件人: eaglexiang/eagle.tunnel.dotnet.core
抄送: Subscribed
主题: [eaglexiang/eagle.tunnel.dotnet.core] 第一步配置就出了问题 (#5)


老板，对于我们这种小白，能否开发一个一键脚本哈？？
我第一步 sudo ./scripts/dotnet/centos.sh 就提示没有这个命令
一脸懵逼啊，我也你一样用的也是vultr 的服务器，Linux版本都一样。

这个隧道那么好，我还是希望能方便我们这种小白哈。

**Comment by banbadaowd** [comment]
快点出一键哈，今天又开始墙了
