### ISSUE TITLE
考不考虑服务端直接提供socks5的代理

### ISSUE THREAD

**Issue by lizhaode** [eaglexiang/eagle.tunnel.dotnet.core#8]
iOS手机上使用还没有兼容的方式，如果是服务端直接开启socks5的代理的话，随便一个手机上的代理软件就支持了

**Comment by eaglexiang** [comment]
是的，暂时还没有iOS客户端。不过电脑是可以共享代理服务给网络的

**Comment by eaglexiang** [comment]
服务器直接提供代理，会被GFW屏蔽掉

**Comment by lizhaode** [comment]
如果提供的是加密的sock5代理呢？GFW还是可以轻松的检测到吗？

**Comment by lizhaode** [comment]
刚刚做了一个简单的对比测试

同一个服务器上，开ss和开eagle，打开YouTube8K视频

我发现ss能马上到4M~5M的速度

eagle会先停留在1M ~ 2M的速度一会，然后才能到4M ~ 5M的速度。

我本地的宽带是联通50M的

感觉是不是eagle在数据包收发上可以做一点事情，因为翻墙用的话，对速度还是挺敏感的

**Comment by eaglexiang** [comment]
是的，还是会被检测到

**Comment by eaglexiang** [comment]
谢谢对比测试，如果找到原因了会尽快优化的

**Comment by eaglexiang** [comment]
如果vps允许的话，推荐启用Google BBR，对速度会有很大帮助

**Comment by lizhaode** [comment]
@eaglexiang 
是开启BBR呢，内核是4.14版本的，如果有更多的测试想法，也可以一起测一下
ps 我个人对这种速度的测试不擅长，包括测试大包 小包的发包效率，速度等测试不太有概念

**Comment by eaglexiang** [comment]
这么长时间过去，基本可以确定你提到的慢启动现象（刚开始速度慢）是因为ET并没有像SS那样保持长连接。而是每当有需求时再去临时建立连接。

这样做的好处是代码结构比较简单，并且更不容易被GFW识别。当然，缺点就是你看到的那样，每次连接刚建立时，速度会有逐步提升的过程。

**Comment by lizhaode** [comment]
原来如此，其实唯一会出现问题的地方就是浏览网页这种场景了，他会频繁的断开/建立链接
